name: Draw Keymaps
on:
  workflow_dispatch:  # can be triggered manually
  push:               # automatically run on changes to following paths
    paths:
      - "drawing/*.yaml"
      - "crkbd.json"
      - "makefile"

jobs:
  draw:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    strategy:
      fail-fast: false

    steps:
    - name: Install keymap-drawer (pypi)
      run: python3 -m pip install keymap-drawer

    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Draw Keymep
      run: make draw-keymaps

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Adds generated keyboard layout files"
  